/**
 * HTML email templates for admission notifications
 * Matches the WhatsApp notification templates but with richer formatting
 */

const baseStyle = `
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; background: #f5f5f5; margin: 0; padding: 0; }
  .container { max-width: 560px; margin: 24px auto; background: #ffffff; border-radius: 16px; overflow: hidden; box-shadow: 0 2px 12px rgba(0,0,0,0.08); }
  .header { background: linear-gradient(135deg, #059669, #0d9488); color: #fff; padding: 32px 24px; text-align: center; }
  .header h1 { margin: 0; font-size: 22px; font-weight: 600; }
  .header p { margin: 8px 0 0; opacity: 0.9; font-size: 14px; }
  .body { padding: 28px 24px; color: #333; line-height: 1.6; }
  .detail-box { background: #f0fdf4; border: 1px solid #bbf7d0; border-radius: 12px; padding: 16px; margin: 16px 0; }
  .detail-box.rejected { background: #fef2f2; border-color: #fecaca; }
  .detail-box.review { background: #eff6ff; border-color: #bfdbfe; }
  .detail-row { display: flex; justify-content: space-between; padding: 6px 0; font-size: 14px; }
  .detail-label { color: #666; }
  .detail-value { font-weight: 600; color: #111; }
  .footer { padding: 16px 24px; text-align: center; font-size: 12px; color: #999; border-top: 1px solid #f0f0f0; }
  .badge { display: inline-block; padding: 4px 14px; border-radius: 999px; font-size: 13px; font-weight: 600; }
  .badge-success { background: #d1fae5; color: #065f46; }
  .badge-danger { background: #fee2e2; color: #991b1b; }
  .badge-info { background: #dbeafe; color: #1e40af; }
`

function wrapHtml(content) {
  return `<!DOCTYPE html>
<html>
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width, initial-scale=1"><style>${baseStyle}</style></head>
<body>${content}</body>
</html>`
}

export const emailTemplates = {
  admissionReceived: ({ parentName, studentName, applicationNumber, schoolName }) => {
    const subject = `Application Received — ${applicationNumber}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header">
          <h1>📋 Application Successful</h1>
          <p>Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Dear <strong>${parentName}</strong>,</p>
          <p>Thank you for enrolling your child at <strong>Chung Chung Christian School</strong>.</p>
          
          <div class="detail-box">
            <div class="detail-row"><span class="detail-label">Student Name</span><span class="detail-value">${studentName}</span></div>
            <div class="detail-row"><span class="detail-label">Application No.</span><span class="detail-value">${applicationNumber}</span></div>
            <div class="detail-row"><span class="detail-label">Target School</span><span class="detail-value">${schoolName || '-'}</span></div>
          </div>
          
          <p>We will review your application shortly and inform you of the result via email or WhatsApp.</p>
          <p>Please keep your application number <strong>${applicationNumber}</strong> to check your application status.</p>
        </div>
        <div class="footer">
          This message is automatically generated by the CCS System — Chung Chung Christian School
        </div>
      </div>
    `)
    return { subject, html }
  },

  admissionRegistrationPayment: ({
    parentName,
    parentEmail,
    parentPhone,
    studentName,
    applicationNumber,
    levelName,
    feeAmount = 250000,
    hostingUrl = 'https://ccs.sch.id/registrasi'
  }) => {
    const formattedAmount = `Rp ${Number(feeAmount || 250000).toLocaleString('id-ID')}`
    const queryTarget = parentEmail || applicationNumber
    const queryPhone = parentPhone ? `&phone=${encodeURIComponent(parentPhone)}` : ''
    const checkUrl = `${String(hostingUrl || 'https://ccs.sch.id/registrasi').replace(/\/$/, '')}/?cek=${encodeURIComponent(queryTarget)}${queryPhone}#tempat-unggah`
    const subject = `Instruksi Pembayaran Pendaftaran Siswa Baru CCS — ${applicationNumber}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #1e3a8a, #0369a1); color: #fff; padding: 28px 24px; text-align: center;">
          <h1 style="margin:0; font-size: 20px; font-weight: 700; color: #ffffff;">Chung Chung Christian School</h1>
          <p style="margin:6px 0 0; opacity: 0.9; font-size: 13px; color: #e0f2fe;">Pendaftaran Siswa Baru (PPDB / SPMB)</p>
        </div>
        <div class="body" style="padding: 24px; color: #334155; line-height: 1.6;">
          <p>Yth. Bapak/Ibu <strong>${parentName || 'Orang Tua / Wali Calon Siswa'}</strong>,</p>
          <p>Terima kasih telah mengajukan pendaftaran siswa baru di <strong>Chung Chung Christian School</strong>. Pendaftaran awal Anda telah tercatat dengan rincian sebagai berikut:</p>
          
          <div class="detail-box" style="background: #f8fafc; border: 1px solid #e2e8f0; border-radius: 12px; padding: 16px; margin: 16px 0;">
            <div class="detail-row" style="display:flex; justify-content:space-between; padding:6px 0; border-bottom: 1px dashed #e2e8f0; font-size: 14px;">
              <span class="detail-label" style="color:#64748b;">Nomor Registrasi:</span>
              <span class="detail-value" style="font-weight:700; font-family:monospace; color:#0f172a; font-size: 15px;">${applicationNumber}</span>
            </div>
            <div class="detail-row" style="display:flex; justify-content:space-between; padding:6px 0; border-bottom: 1px dashed #e2e8f0; font-size: 14px;">
              <span class="detail-label" style="color:#64748b;">Nama Calon Siswa:</span>
              <span class="detail-value" style="font-weight:600; color:#0f172a;">${studentName}</span>
            </div>
            <div class="detail-row" style="display:flex; justify-content:space-between; padding:6px 0; border-bottom: 1px dashed #e2e8f0; font-size: 14px;">
              <span class="detail-label" style="color:#64748b;">Jenjang Pilihan:</span>
              <span class="detail-value" style="font-weight:600; color:#0f172a;">${levelName || '-'}</span>
            </div>
            <div class="detail-row" style="display:flex; justify-content:space-between; padding:6px 0; font-size: 14px;">
              <span class="detail-label" style="color:#64748b;">Biaya Pembelian Formulir:</span>
              <span class="detail-value" style="font-weight:700; color:#ea580c; font-size: 15px;">${formattedAmount}</span>
            </div>
          </div>

          <div style="background: #eff6ff; border: 1px solid #bfdbfe; border-radius: 12px; padding: 18px; margin: 20px 0;">
            <div style="font-size: 12px; font-weight: 700; color: #1e40af; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px;">
              🏦 Rekening Resmi Pembayaran Sekolah
            </div>
            <div style="font-size: 16px; font-weight: 700; color: #1e3a8a; margin-bottom: 4px;">Bank Mayapada</div>
            <div style="font-size: 20px; font-weight: 700; font-family: monospace; color: #0284c7; letter-spacing: 1px; margin-bottom: 6px;">
              100-3000-3853
            </div>
            <div style="font-size: 13px; color: #334155;">
              Atas Nama: <strong>Yayasan Pendidikan Mayapada School</strong>
            </div>
            <div style="font-size: 12px; color: #64748b; margin-top: 4px;">
              Berita Transfer: <code style="background:#dbeafe; padding: 2px 6px; border-radius: 4px; font-weight: 600;">${applicationNumber} ${studentName}</code>
            </div>
          </div>

          <div style="margin: 24px 0 16px; text-align: center;">
            <a href="${checkUrl}" style="background-color: #f37021; color: #ffffff; text-decoration: none; padding: 13px 26px; border-radius: 10px; font-weight: 700; font-size: 14px; display: inline-block;">
              📤 Unggah Bukti Pembayaran
            </a>
          </div>

          <p style="font-size: 13px; color: #64748b; margin-top: 16px; line-height: 1.5;">
            <strong>Langkah Selanjutnya:</strong><br/>
            1. Silakan lakukan transfer sejumlah <strong>${formattedAmount}</strong> ke rekening Bank Mayapada di atas.<br/>
            2. Klik tombol di atas untuk membuka status registrasi Anda dan mengunggah foto / file bukti transfer.<br/>
            3. Tim admisi sekolah akan memverifikasi pembayaran Anda, setelah itu Anda dapat melanjutkan pengisian biodata lengkap siswa.
          </p>

          <p style="font-size: 12px; color: #94a3b8; margin-top: 16px;">
            Tautan Cek Status: <a href="${checkUrl}" style="color: #0284c7; word-break: break-all;">${checkUrl}</a>
          </p>
        </div>
        <div class="footer" style="padding: 16px 24px; text-align: center; font-size: 12px; color: #94a3b8; border-top: 1px solid #f1f5f9;">
          Chung Chung Christian School &bull; Yayasan Pendidikan Mayapada School &bull; Hotline: +62 859-5986-0430
        </div>
      </div>
    `)
    return { subject, html }
  },

  admissionApproved: ({ parentName, studentName, applicationNumber }) => {
    const subject = `🎉 Application Approved — ${applicationNumber}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header">
          <h1>🎉 Application Approved!</h1>
          <p>Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Dear <strong>${parentName}</strong>,</p>
          <p>Congratulations! Your child's application has been <span class="badge badge-success">APPROVED</span>.</p>
          
          <div class="detail-box">
            <div class="detail-row"><span class="detail-label">Student Name</span><span class="detail-value">${studentName}</span></div>
            <div class="detail-row"><span class="detail-label">Application No.</span><span class="detail-value">${applicationNumber}</span></div>
          </div>
          
          <p>Please contact the school for the next steps.</p>
        </div>
        <div class="footer">
          This message is automatically generated by the CCS System — Chung Chung Christian School
        </div>
      </div>
    `)
    return { subject, html }
  },

  admissionRejected: ({ parentName, studentName, applicationNumber }) => {
    const subject = `Application Update — ${applicationNumber}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #dc2626, #ef4444);">
          <h1>Application Update</h1>
          <p>Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Dear <strong>${parentName}</strong>,</p>
          <p>We regret to inform you that your child's application <span class="badge badge-danger">cannot be accepted</span> at this time.</p>
          
          <div class="detail-box rejected">
            <div class="detail-row"><span class="detail-label">Student Name</span><span class="detail-value">${studentName}</span></div>
            <div class="detail-row"><span class="detail-label">Application No.</span><span class="detail-value">${applicationNumber}</span></div>
          </div>
          
          <p>Please contact the school for further information.</p>
        </div>
        <div class="footer">
          This message is automatically generated by the CCS System — Chung Chung Christian School
        </div>
      </div>
    `)
    return { subject, html }
  },

  admissionUnderReview: ({ parentName, studentName, applicationNumber }) => {
    const subject = `Application Under Review — ${applicationNumber}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #2563eb, #3b82f6);">
          <h1>📝 Under Review</h1>
          <p>Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Dear <strong>${parentName}</strong>,</p>
          <p>Your child's application is currently <span class="badge badge-info">under review</span>.</p>
          
          <div class="detail-box review">
            <div class="detail-row"><span class="detail-label">Student Name</span><span class="detail-value">${studentName}</span></div>
            <div class="detail-row"><span class="detail-label">Application No.</span><span class="detail-value">${applicationNumber}</span></div>
          </div>
          
          <p>We will inform you of the result via email or WhatsApp shortly.</p>
        </div>
        <div class="footer">
          This message is automatically generated by the CCS System — Chung Chung Christian School
        </div>
      </div>
    `)
    return { subject, html }
  },

  // ─── Attendance Notification Templates ────────────────────────────────────

  /**
   * Sent to the individual user (teacher/staff) who had an attendance issue
   * @param {object} params
   * @param {string} params.userName - Full name of the user
   * @param {string} params.date - Date string (e.g. "Kamis, 19 Juni 2026")
   * @param {Array}  params.issues - Array of issue objects: { type, scheduledTime, actualTime, minutesDiff }
   */
  attendanceLate: ({ userName, date, issues, baseUrl }) => {
    const typeLabel = (type) => {
      switch (type) {
        case 'late':        return { icon: '🕐', label: 'Late Attendance',    engLabel: 'Late Attendance',    color: '#d97706', bg: '#fef3c7', headerGrad: 'linear-gradient(135deg, #d97706, #f59e0b)' }
        case 'leave_early': return { icon: '🚪', label: 'Early Dismissal',     engLabel: 'Early Dismissal',     color: '#dc2626', bg: '#fee2e2', headerGrad: 'linear-gradient(135deg, #dc2626, #ef4444)' }
        case 'absent':      return { icon: '🚫', label: 'Absence',            engLabel: 'Absence',            color: '#6b21a8', bg: '#f3e8ff', headerGrad: 'linear-gradient(135deg, #6b21a8, #9333ea)' }
        case 'no_checkin':  return { icon: '❌', label: 'Missing Check-In',   engLabel: 'Missing Check-In',   color: '#7c3aed', bg: '#ede9fe', headerGrad: 'linear-gradient(135deg, #7c3aed, #8b5cf6)' }
        case 'no_checkout': return { icon: '⚠️', label: 'Missing Check-Out',  engLabel: 'Missing Check-Out',  color: '#ea580c', bg: '#ffedd5', headerGrad: 'linear-gradient(135deg, #ea580c, #f97316)' }
        default:            return { icon: '❓', label: type,                  engLabel: type,                 color: '#374151', bg: '#f3f4f6', headerGrad: 'linear-gradient(135deg, #6b7280, #9ca3af)' }
      }
    }

    const issueList = issues || []
    const primaryMeta = typeLabel(issueList[0]?.type || 'late')

    const engLabels = issueList.map(i => typeLabel(i.type).engLabel)
    const subject = issueList.length === 1
      ? `Notice of ${engLabels[0]}`
      : `Notice of ${engLabels.join(' & ')}`

    // Build badges to place at the top of the body
    const badgesHtml = issueList.map(issue => {
      const { label } = typeLabel(issue.type)
      return `<span style="background:#fef08a;padding:4px 10px;border-radius:4px;font-weight:600;font-size:13px;display:inline-block;margin-right:6px;">${label}</span>`
    }).join(' ')

    // Build factual, neutral sentence per issue
    const issueLines = issueList.map(issue => {
      const { label } = typeLabel(issue.type)

      if (issue.type === 'late') {
        const actual = issue.actualTime || '—'
        const scheduled = issue.scheduledTime || '—'
        return `On <strong>${date}</strong>, your check-in time was recorded at <strong>${actual}</strong>. Your scheduled check-in time is at <strong>${scheduled}</strong>.`
      } else if (issue.type === 'leave_early') {
        const actual = issue.actualTime || '—'
        const scheduled = issue.scheduledTime || '—'
        return `On <strong>${date}</strong>, your check-out time was recorded at <strong>${actual}</strong>. Your scheduled check-out time is at <strong>${scheduled}</strong>.`
      } else if (issue.type === 'absent') {
        return `On <strong>${date}</strong>, no attendance record was found for your account.`
      } else if (issue.type === 'no_checkin') {
        const scheduled = issue.scheduledTime || '—'
        return `On <strong>${date}</strong>, there is no check-in record found. Your scheduled check-in time is at <strong>${scheduled}</strong>.`
      } else if (issue.type === 'no_checkout') {
        const scheduled = issue.scheduledTime || '—'
        return `On <strong>${date}</strong>, there is no check-out record found. Your scheduled check-out time is at <strong>${scheduled}</strong>.`
      }
      return `On <strong>${date}</strong>, a <strong>${label}</strong> was recorded.`
    })

    // Portal URL
    const portalUrl = `${baseUrl || 'https://manageccs.online'}/data/attendance-form`

    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: ${primaryMeta.headerGrad};">
          <h1>${issueList.length === 1 ? `${primaryMeta.icon} ${primaryMeta.engLabel}` : '⚠️ Attendance Notice'}</h1>
          <p>Chung Chung Christian School</p>
        </div>
        <div class="body">
          <div style="margin-bottom: 14px;">${badgesHtml}</div>
          <p>Good Morning, <strong>${userName}</strong>.</p>
          ${issueLines.map(l => `<p style="margin:10px 0;">${l}</p>`).join('')}
          <p style="margin-top:20px;">
            Please complete the attendance excuse form in the CCS Portal:<br>
            <a href="${portalUrl}" style="color:#1d4ed8;word-break:break-all;">${portalUrl}</a>
          </p>
          <p style="margin-top:20px;color:#444;">
            HCM Chung Chung Christian School
          </p>
          <p style="margin-top:12px;font-size:12px;color:#999;">
            This email was sent to you by <strong>Chung Chung Christian School</strong>.
            We kindly request that you <em>do not mark this email as spam.</em>
          </p>
        </div>
        <div class="footer">
          HCM Chung Chung Christian School
        </div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Sent to admin/HR with a summary table of all attendance violations for the day
   * @param {object} params
   * @param {string} params.date - Date string (e.g. "Kamis, 19 Juni 2026")
   * @param {Array}  params.violations - Array of { userName, roleName, unitName, type, scheduledTime, actualTime, minutesDiff }
   */
  attendanceSummaryAdmin: ({ date, violations }) => {
    // date is already pre-formatted (e.g. "Tuesday, 14 July 2026") by the notify route
    const subject = `📋 Daily Attendance Summary — ${date} — ${violations.length} violation(s)`

    const typeLabel = (type) => {
      switch (type) {
        case 'late':        return '🕐 Late'
        case 'leave_early': return '🚪 Early Dismissal'
        case 'absent':      return '🚫 Absent'
        case 'no_checkin':  return '❌ Missing Check-In'
        case 'no_checkout': return '⚠️ Missing Check-Out'
        default:            return type
      }
    }

    const rows = (violations || []).map((v, i) => {
      const bgColor = i % 2 === 0 ? '#f9fafb' : '#ffffff'
      const detail = (v.type === 'absent' || v.type === 'no_checkin' || v.type === 'no_checkout')
        ? '—'
        : `${v.actualTime} (${v.minutesDiff > 0 ? '+' : ''}${v.minutesDiff} min)`
      return `
        <tr style="background:${bgColor}">
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;">${v.userName}</td>
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;color:#6b7280;">${v.roleName || '-'}</td>
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;color:#6b7280;">${v.unitName || '-'}</td>
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;">${typeLabel(v.type)}</td>
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;color:#6b7280;">${v.scheduledTime || '—'}</td>
          <td style="padding:8px 12px;font-size:13px;border-bottom:1px solid #f0f0f0;">${detail}</td>
        </tr>`
    }).join('')

    const html = wrapHtml(`
      <div class="container" style="max-width:720px;">
        <div class="header" style="background: linear-gradient(135deg, #1e40af, #3b82f6);">
          <h1>📋 Daily Attendance Summary</h1>
          <p>Chung Chung Christian School — ${date}</p>
        </div>
        <div class="body">
          <p>The following attendance violations were recorded on <strong>${date}</strong>:</p>
          <div class="detail-box" style="padding:0;overflow:hidden;">
            <table style="width:100%;border-collapse:collapse;">
              <thead>
                <tr style="background:#f0f9ff;">
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Name</th>
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Role</th>
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Unit</th>
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Type</th>
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Scheduled</th>
                  <th style="padding:10px 12px;font-size:12px;text-align:left;color:#374151;border-bottom:2px solid #e5e7eb;">Actual</th>
                </tr>
              </thead>
              <tbody>${rows}</tbody>
            </table>
          </div>
          <p style="font-size:13px;color:#666;margin-top:16px;">
            Total: <strong>${violations.length} record(s)</strong> from the attendance machine on ${date}.
          </p>
        </div>
        <div class="footer">
          This summary is sent automatically every day at 00:01 WIB — CCS Attendance System
        </div>
      </div>
    `)
    return { subject, html }
  },

  // ─── FPB Templates ───────────────────────────────────────────────────────────

  /**
   * Email to approver: a new FPB is waiting for their action
   * params: { approverName, fpbNumber, fpbType, submitterName, division, grandTotal, usageDate, stepName, appUrl }
   */
  fpbPendingApproval: ({ approverName, fpbNumber, fpbType, submitterName, division, grandTotal, usageDate, stepName, appUrl }) => {
    const subject = `[Action Required] FPB ${fpbNumber} requires your approval`
    const fmtCurrency = (n) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n || 0)
    const fmtDate = (d) => d ? new Date(d).toLocaleDateString('en-GB', { day: '2-digit', month: 'long', year: 'numeric' }) : '—'
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #6366f1, #8b5cf6);">
          <h1>📋 Approval Required</h1>
          <p>Purchase Request Form (FPB)</p>
        </div>
        <div class="body">
          <p>Dear <strong>${approverName}</strong>,</p>
          <p>A new FPB requires your action at the <strong>${stepName}</strong> stage.</p>
          <div class="detail-box review">
            <div class="detail-row"><span class="detail-label">FPB Number</span><span class="detail-value">${fpbNumber}</span></div>
            <div class="detail-row"><span class="detail-label">Type</span><span class="detail-value">${fpbType || '—'}</span></div>
            <div class="detail-row"><span class="detail-label">Requested By</span><span class="detail-value">${submitterName}</span></div>
            <div class="detail-row"><span class="detail-label">Division</span><span class="detail-value">${division || '—'}</span></div>
            <div class="detail-row"><span class="detail-label">Total Amount</span><span class="detail-value">${fmtCurrency(grandTotal)}</span></div>
            <div class="detail-row"><span class="detail-label">Usage Date</span><span class="detail-value">${fmtDate(usageDate)}</span></div>
          </div>
          <p style="text-align:center;margin-top:20px;">
            <a href="${appUrl || 'https://manageccs.online/data/fpb'}"
              style="display:inline-block;padding:12px 28px;background:#6366f1;color:#fff;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px;">
              View & Review FPB
            </a>
          </p>
        </div>
        <div class="footer">Automated notification — CCS Admin System</div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Email to submitter: their FPB has been fully approved
   * params: { submitterName, fpbNumber, fpbType, grandTotal, appUrl }
   */
  fpbApproved: ({ submitterName, fpbNumber, fpbType, grandTotal, appUrl }) => {
    const subject = `[Approved] FPB ${fpbNumber} has been fully approved`
    const fmtCurrency = (n) => new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', maximumFractionDigits: 0 }).format(n || 0)
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #059669, #0d9488);">
          <h1>✅ FPB Approved</h1>
          <p>Purchase Request Form (FPB)</p>
        </div>
        <div class="body">
          <p>Dear <strong>${submitterName}</strong>,</p>
          <p>Congratulations! Your FPB has been <strong>fully approved</strong> by all approvers.</p>
          <div class="detail-box">
            <div class="detail-row"><span class="detail-label">FPB Number</span><span class="detail-value">${fpbNumber}</span></div>
            <div class="detail-row"><span class="detail-label">Type</span><span class="detail-value">${fpbType || '—'}</span></div>
            <div class="detail-row"><span class="detail-label">Total Amount</span><span class="detail-value">${fmtCurrency(grandTotal)}</span></div>
            <div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge badge-success">Approved</span></span></div>
          </div>
          <p style="text-align:center;margin-top:20px;">
            <a href="${appUrl || 'https://manageccs.online/data/fpb'}"
              style="display:inline-block;padding:12px 28px;background:#059669;color:#fff;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px;">
              View FPB Details
            </a>
          </p>
        </div>
        <div class="footer">Automated notification — CCS Admin System</div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Email to submitter: their FPB requires revision
   * params: { submitterName, fpbNumber, fpbType, approverName, comment, appUrl }
   */
  fpbRevision: ({ submitterName, fpbNumber, fpbType, approverName, comment, appUrl }) => {
    const subject = `[Revision Required] FPB ${fpbNumber} requires revision`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #d97706, #f59e0b);">
          <h1>↩ FPB Revision Required</h1>
          <p>Purchase Request Form (FPB)</p>
        </div>
        <div class="body">
          <p>Dear <strong>${submitterName}</strong>,</p>
          <p>Your FPB has been <strong>returned for revision</strong>. Please update and resubmit.</p>
          <div class="detail-box review">
            <div class="detail-row"><span class="detail-label">FPB Number</span><span class="detail-value">${fpbNumber}</span></div>
            <div class="detail-row"><span class="detail-label">Type</span><span class="detail-value">${fpbType || '—'}</span></div>
            <div class="detail-row"><span class="detail-label">From Approver</span><span class="detail-value">${approverName}</span></div>
          </div>
          ${comment ? `
          <div style="margin-top:12px;padding:12px 16px;background:#fef3c7;border-left:4px solid #d97706;border-radius:6px;font-size:13px;color:#92400e;">
            <strong>Approver's Note:</strong><br>${comment}
          </div>` : ''}
          <p style="text-align:center;margin-top:20px;">
            <a href="${appUrl || 'https://manageccs.online/data/fpb'}"
              style="display:inline-block;padding:12px 28px;background:#d97706;color:#fff;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px;">
              Update FPB
            </a>
          </p>
        </div>
        <div class="footer">Automated notification — CCS Admin System</div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Email to submitter: their FPB has been rejected
   * params: { submitterName, fpbNumber, fpbType, approverName, comment, appUrl }
   */
  fpbRejected: ({ submitterName, fpbNumber, fpbType, approverName, comment, appUrl }) => {
    const subject = `[Rejected] FPB ${fpbNumber} has been rejected`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #dc2626, #b91c1c);">
          <h1>✕ FPB Rejected</h1>
          <p>Purchase Request Form (FPB)</p>
        </div>
        <div class="body">
          <p>Dear <strong>${submitterName}</strong>,</p>
          <p>Your FPB <strong>cannot be processed</strong> because it was rejected by the approver.</p>
          <div class="detail-box rejected">
            <div class="detail-row"><span class="detail-label">FPB Number</span><span class="detail-value">${fpbNumber}</span></div>
            <div class="detail-row"><span class="detail-label">Type</span><span class="detail-value">${fpbType || '—'}</span></div>
            <div class="detail-row"><span class="detail-label">Rejected By</span><span class="detail-value">${approverName}</span></div>
            <div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge badge-danger">Rejected</span></span></div>
          </div>
          ${comment ? `
          <div style="margin-top:12px;padding:12px 16px;background:#fef2f2;border-left:4px solid #dc2626;border-radius:6px;font-size:13px;color:#991b1b;">
            <strong>Reason for Rejection:</strong><br>${comment}
          </div>` : ''}
          <p style="text-align:center;margin-top:20px;">
            <a href="${appUrl || 'https://manageccs.online/data/fpb'}"
              style="display:inline-block;padding:12px 28px;background:#dc2626;color:#fff;border-radius:8px;text-decoration:none;font-weight:700;font-size:14px;">
              View FPB Details
            </a>
          </p>
        </div>
        <div class="footer">Automated notification — CCS Admin System</div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Email to renter: their court booking has been approved
   * params: { renterName, bookingCode, packageName, price, bookingDate, timeSlot }
   */
  courtRentalApproved: ({ renterName, bookingCode, packageName, price, bookingDate, timeSlot }) => {
    const formattedPrice = typeof price === 'number' ? `Rp ${price.toLocaleString('id-ID')},-` : (price || '—')
    const subject = `🎉 Konfirmasi Resmi Sewa Lapangan CCS — ${bookingCode}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #1e3a8a, #ea580c);">
          <h1>✓ Reservasi Lapangan Disetujui!</h1>
          <p>Sport Hall — Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Yth. <strong>${renterName}</strong>,</p>
          <p>Terima kasih telah melakukan pembayaran. Permohonan sewa lapangan olahraga CCS Anda telah diverifikasi dan <span class="badge badge-success">DISETUJUI</span>.</p>
          
          <div class="detail-box">
            <div class="detail-row"><span class="detail-label">Kode Booking</span><span class="detail-value" style="font-family: monospace; font-size: 15px; color: #ea580c;">${bookingCode}</span></div>
            <div class="detail-row"><span class="detail-label">Paket Sewa</span><span class="detail-value">${packageName}</span></div>
            <div class="detail-row"><span class="detail-label">Total Biaya</span><span class="detail-value">${formattedPrice}</span></div>
            <div class="detail-row"><span class="detail-label">Tanggal Bermain</span><span class="detail-value">${bookingDate}</span></div>
            <div class="detail-row"><span class="detail-label">Sesi Jam</span><span class="detail-value">${timeSlot}</span></div>
            <div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge badge-success">Sukses / Disetujui</span></span></div>
          </div>

          <div style="margin-top:16px;padding:14px 18px;background:#f8fafc;border-left:4px solid #1e3a8a;border-radius:8px;font-size:13px;color:#334155;line-height:1.6;">
            <strong>Ketentuan Penting Memasuki Area Lapangan:</strong>
            <ul style="margin:6px 0 0 0;padding-left:18px;">
              <li>Tunjukkan email konfirmasi resmi ini beserta Kode Booking kepada petugas keamanan/lapangan saat tiba di sekolah.</li>
              <li>Penyewa diminta meninggalkan area lapangan dan sekolah dalam kondisi bersih seperti semula (denda Rp 50.000 jika kotor).</li>
              <li>Dilarang keras merokok di seluruh area lapangan dan lingkungan sekolah.</li>
              <li>Penggunaan AC dan/atau lampu dinyalakan tepat sesuai dengan jam sewa yang terdaftar.</li>
            </ul>
          </div>

          <p style="margin-top:20px;font-size:13px;color:#64748b;">
            Jika ada pertanyaan atau kendala mengenai reservasi ini, silakan hubungi Contact Person resmi: <strong>+62 859-5986-0430</strong>.
          </p>
        </div>
        <div class="footer">
          Yayasan Pendidikan Mayapada School — Chung Chung Christian School (CCS)
        </div>
      </div>
    `)
    return { subject, html }
  },

  /**
   * Email to renter: their court booking has been rejected
   * params: { renterName, bookingCode, packageName, bookingDate, timeSlot, reason }
   */
  courtRentalRejected: ({ renterName, bookingCode, packageName, bookingDate, timeSlot, reason }) => {
    const subject = `Pemberitahuan Permohonan Sewa Lapangan CCS — ${bookingCode}`
    const html = wrapHtml(`
      <div class="container">
        <div class="header" style="background: linear-gradient(135deg, #dc2626, #991b1b);">
          <h1>✕ Reservasi Belum Dapat Disetujui</h1>
          <p>Sport Hall — Chung Chung Christian School</p>
        </div>
        <div class="body">
          <p>Yth. <strong>${renterName}</strong>,</p>
          <p>Mohon maaf, permohonan sewa lapangan Anda dengan kode <strong>${bookingCode}</strong> belum dapat disetujui oleh pihak pengelola.</p>
          
          <div class="detail-box rejected">
            <div class="detail-row"><span class="detail-label">Kode Booking</span><span class="detail-value" style="font-family: monospace;">${bookingCode}</span></div>
            <div class="detail-row"><span class="detail-label">Paket</span><span class="detail-value">${packageName}</span></div>
            <div class="detail-row"><span class="detail-label">Jadwal</span><span class="detail-value">${bookingDate} (${timeSlot})</span></div>
            <div class="detail-row"><span class="detail-label">Status</span><span class="detail-value"><span class="badge badge-danger">Ditolak</span></span></div>
          </div>

          ${reason ? `
          <div style="margin-top:14px;padding:12px 16px;background:#fef2f2;border-left:4px solid #dc2626;border-radius:6px;font-size:13px;color:#991b1b;">
            <strong>Catatan Petugas:</strong><br>${reason}
          </div>` : ''}

          <p style="margin-top:20px;font-size:13px;color:#64748b;">
            Untuk informasi lebih lanjut atau pengembalian dana jika pembayaran telah terpotong, silakan menghubungi Contact Person: <strong>+62 859-5986-0430</strong>.
          </p>
        </div>
        <div class="footer">
          Yayasan Pendidikan Mayapada School — Chung Chung Christian School (CCS)
        </div>
      </div>
    `)
    return { subject, html }
  }
}
