-- Migration: Create PYP Unit Assessment & ATL Assessment Tables
-- Date: 2026-08-26

-- 1. Table for Unit of Inquiry Overall Student Assessment
CREATE TABLE IF NOT EXISTS public.pyp_unit_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL REFERENCES public.pyp_unit(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    year_id BIGINT NOT NULL REFERENCES public.year(year_id) ON DELETE CASCADE,
    kelas_id BIGINT NOT NULL REFERENCES public.kelas(kelas_id) ON DELETE CASCADE,
    semester SMALLINT NOT NULL DEFAULT 1,
    rating VARCHAR(50) NOT NULL DEFAULT 'N/A', -- 'N/A', 'Beginning', 'Developing', 'Achieving', 'Exceeding'
    notes TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    CONSTRAINT uq_pyp_unit_assessment UNIQUE (unit_id, student_id)
);

-- 2. Table for Approaches to Learning (ATL) Student Assessment per Unit
CREATE TABLE IF NOT EXISTS public.pyp_atl_assessment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    unit_id BIGINT NOT NULL REFERENCES public.pyp_unit(id) ON DELETE CASCADE,
    atl_id BIGINT NOT NULL REFERENCES public.pyp_atls_list(id) ON DELETE CASCADE,
    student_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
    year_id BIGINT NOT NULL REFERENCES public.year(year_id) ON DELETE CASCADE,
    kelas_id BIGINT NOT NULL REFERENCES public.kelas(kelas_id) ON DELETE CASCADE,
    semester SMALLINT NOT NULL DEFAULT 1,
    rating VARCHAR(50) NOT NULL DEFAULT 'N/A', -- 'N/A', 'Beginning', 'Developing', 'Achieving', 'Exceeding'
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    created_by BIGINT,
    updated_at TIMESTAMPTZ,
    updated_by BIGINT,
    CONSTRAINT uq_pyp_atl_assessment UNIQUE (unit_id, atl_id, student_id)
);

-- Indices for rapid lookups and report generation
CREATE INDEX IF NOT EXISTS idx_pyp_unit_assess_unit_student ON public.pyp_unit_assessment(unit_id, student_id);
CREATE INDEX IF NOT EXISTS idx_pyp_unit_assess_kelas_sem ON public.pyp_unit_assessment(kelas_id, semester);
CREATE INDEX IF NOT EXISTS idx_pyp_atl_assess_unit_atl_student ON public.pyp_atl_assessment(unit_id, atl_id, student_id);
CREATE INDEX IF NOT EXISTS idx_pyp_atl_assess_kelas_sem ON public.pyp_atl_assessment(kelas_id, semester);

-- Enable RLS & Permissive Access Policies
ALTER TABLE public.pyp_unit_assessment ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pyp_atl_assessment ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all select pyp_unit_assessment" ON public.pyp_unit_assessment;
DROP POLICY IF EXISTS "Allow all insert pyp_unit_assessment" ON public.pyp_unit_assessment;
DROP POLICY IF EXISTS "Allow all update pyp_unit_assessment" ON public.pyp_unit_assessment;
DROP POLICY IF EXISTS "Allow all delete pyp_unit_assessment" ON public.pyp_unit_assessment;

CREATE POLICY "Allow all select pyp_unit_assessment" ON public.pyp_unit_assessment FOR SELECT USING (true);
CREATE POLICY "Allow all insert pyp_unit_assessment" ON public.pyp_unit_assessment FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pyp_unit_assessment" ON public.pyp_unit_assessment FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pyp_unit_assessment" ON public.pyp_unit_assessment FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow all select pyp_atl_assessment" ON public.pyp_atl_assessment;
DROP POLICY IF EXISTS "Allow all insert pyp_atl_assessment" ON public.pyp_atl_assessment;
DROP POLICY IF EXISTS "Allow all update pyp_atl_assessment" ON public.pyp_atl_assessment;
DROP POLICY IF EXISTS "Allow all delete pyp_atl_assessment" ON public.pyp_atl_assessment;

CREATE POLICY "Allow all select pyp_atl_assessment" ON public.pyp_atl_assessment FOR SELECT USING (true);
CREATE POLICY "Allow all insert pyp_atl_assessment" ON public.pyp_atl_assessment FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pyp_atl_assessment" ON public.pyp_atl_assessment FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pyp_atl_assessment" ON public.pyp_atl_assessment FOR DELETE USING (true);
