-- Migration: Create 4 PYP Unit Pivot Junction Tables for Supabase (PostgreSQL)
-- Date: 2026-08-13

-- 1. Pivot Unit ↔ Line of Inquiry
CREATE TABLE IF NOT EXISTS public.pyploiunit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "unitId" bigint NOT NULL,
    "loiId" bigint NOT NULL,
    is_deleted smallint NOT NULL DEFAULT 0,
    createdat timestamp with time zone NOT NULL DEFAULT now(),
    createdby bigint NOT NULL DEFAULT 2,
    updatedat timestamp with time zone,
    updatedby bigint,
    deletedat timestamp with time zone,
    deletedby bigint
);

-- 2. Pivot Unit ↔ Key Concept
CREATE TABLE IF NOT EXISTS public.pypkcunit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "unitId" bigint NOT NULL,
    "kcId" bigint NOT NULL,
    is_deleted smallint NOT NULL DEFAULT 0,
    createdat timestamp with time zone NOT NULL DEFAULT now(),
    createdby bigint NOT NULL DEFAULT 2,
    updatedat timestamp with time zone,
    updatedby bigint,
    deletedat timestamp with time zone,
    deletedby bigint
);

-- 3. Pivot Unit ↔ Approach to Learning
CREATE TABLE IF NOT EXISTS public.pypatlsunit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "unitId" bigint NOT NULL,
    "atlId" bigint NOT NULL,
    keterangan text,
    is_deleted smallint NOT NULL DEFAULT 0,
    createdat timestamp with time zone NOT NULL DEFAULT now(),
    createdby bigint NOT NULL DEFAULT 2,
    updatedat timestamp with time zone,
    updatedby bigint,
    deletedat timestamp with time zone,
    deletedby bigint
);

-- 4. Pivot Unit ↔ Subject Strand
CREATE TABLE IF NOT EXISTS public.pypstrandsunit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "unitId" bigint NOT NULL,
    "subjectId" bigint NOT NULL,
    "strandId" bigint NOT NULL,
    is_deleted smallint NOT NULL DEFAULT 0,
    createdat timestamp with time zone NOT NULL DEFAULT now(),
    createdby bigint NOT NULL DEFAULT 2,
    updatedat timestamp with time zone,
    updatedby bigint,
    deletedat timestamp with time zone,
    deletedby bigint
);

-- Enable RLS & Permissive Access Policies for Supabase
ALTER TABLE public.pyploiunit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pypkcunit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pypatlsunit ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pypstrandsunit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all select pyploiunit" ON public.pyploiunit;
DROP POLICY IF EXISTS "Allow all insert pyploiunit" ON public.pyploiunit;
DROP POLICY IF EXISTS "Allow all update pyploiunit" ON public.pyploiunit;
DROP POLICY IF EXISTS "Allow all delete pyploiunit" ON public.pyploiunit;

CREATE POLICY "Allow all select pyploiunit" ON public.pyploiunit FOR SELECT USING (true);
CREATE POLICY "Allow all insert pyploiunit" ON public.pyploiunit FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pyploiunit" ON public.pyploiunit FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pyploiunit" ON public.pyploiunit FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow all select pypkcunit" ON public.pypkcunit;
DROP POLICY IF EXISTS "Allow all insert pypkcunit" ON public.pypkcunit;
DROP POLICY IF EXISTS "Allow all update pypkcunit" ON public.pypkcunit;
DROP POLICY IF EXISTS "Allow all delete pypkcunit" ON public.pypkcunit;

CREATE POLICY "Allow all select pypkcunit" ON public.pypkcunit FOR SELECT USING (true);
CREATE POLICY "Allow all insert pypkcunit" ON public.pypkcunit FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pypkcunit" ON public.pypkcunit FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pypkcunit" ON public.pypkcunit FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow all select pypatlsunit" ON public.pypatlsunit;
DROP POLICY IF EXISTS "Allow all insert pypatlsunit" ON public.pypatlsunit;
DROP POLICY IF EXISTS "Allow all update pypatlsunit" ON public.pypatlsunit;
DROP POLICY IF EXISTS "Allow all delete pypatlsunit" ON public.pypatlsunit;

CREATE POLICY "Allow all select pypatlsunit" ON public.pypatlsunit FOR SELECT USING (true);
CREATE POLICY "Allow all insert pypatlsunit" ON public.pypatlsunit FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pypatlsunit" ON public.pypatlsunit FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pypatlsunit" ON public.pypatlsunit FOR DELETE USING (true);

DROP POLICY IF EXISTS "Allow all select pypstrandsunit" ON public.pypstrandsunit;
DROP POLICY IF EXISTS "Allow all insert pypstrandsunit" ON public.pypstrandsunit;
DROP POLICY IF EXISTS "Allow all update pypstrandsunit" ON public.pypstrandsunit;
DROP POLICY IF EXISTS "Allow all delete pypstrandsunit" ON public.pypstrandsunit;

CREATE POLICY "Allow all select pypstrandsunit" ON public.pypstrandsunit FOR SELECT USING (true);
CREATE POLICY "Allow all insert pypstrandsunit" ON public.pypstrandsunit FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pypstrandsunit" ON public.pypstrandsunit FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pypstrandsunit" ON public.pypstrandsunit FOR DELETE USING (true);
