-- Create ATL Descriptors Table
-- This table stores Approaches to Learning skill descriptors
-- Each row represents one descriptor point (atomic)

CREATE TABLE IF NOT EXISTS atl_descriptors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    skill_category TEXT NOT NULL,  -- e.g., 'Communication', 'Social', 'Self-management', 'Research', 'Thinking'
    strand TEXT NOT NULL,          -- e.g., 'Organization', 'Interpersonal'
    cluster TEXT NOT NULL,         -- e.g., 'Managing Self', 'Media Literacy'
    min_grade INTEGER NOT NULL,    -- Minimum grade level (e.g., 6)
    max_grade INTEGER NOT NULL,    -- Maximum grade level (e.g., 8)
    descriptor_text TEXT NOT NULL, -- The actual descriptor text (one point per row)
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    
    -- Constraints
    CONSTRAINT valid_grade_range CHECK (min_grade <= max_grade),
    CONSTRAINT valid_grade_values CHECK (min_grade >= 6 AND max_grade <= 12)
);

-- Create indexes for better query performance
CREATE INDEX IF NOT EXISTS idx_atl_skill_category ON atl_descriptors(skill_category);
CREATE INDEX IF NOT EXISTS idx_atl_grade_range ON atl_descriptors(min_grade, max_grade);
CREATE INDEX IF NOT EXISTS idx_atl_strand ON atl_descriptors(strand);

-- Comments
COMMENT ON TABLE atl_descriptors IS 'Stores IB MYP Approaches to Learning (ATL) skill descriptors in normalized format (one descriptor per row)';
COMMENT ON COLUMN atl_descriptors.skill_category IS 'Main ATL skill category: Communication, Social, Self-management, Research, or Thinking';
COMMENT ON COLUMN atl_descriptors.strand IS 'Sub-category within the skill category';
COMMENT ON COLUMN atl_descriptors.cluster IS 'Specific cluster within the strand';
COMMENT ON COLUMN atl_descriptors.min_grade IS 'Minimum grade level this descriptor applies to (6-12)';
COMMENT ON COLUMN atl_descriptors.max_grade IS 'Maximum grade level this descriptor applies to (6-12)';
COMMENT ON COLUMN atl_descriptors.descriptor_text IS 'The actual descriptor text - one point per row, no bullet points';

-- Sample data (optional - can be removed if not needed)
INSERT INTO atl_descriptors (skill_category, strand, cluster, min_grade, max_grade, descriptor_text) VALUES
('Communication', 'Communication', 'Exchanging thoughts, messages and information effectively through interaction', 6, 8, 'Use appropriate forms of writing for different purposes and audiences'),
('Communication', 'Communication', 'Exchanging thoughts, messages and information effectively through interaction', 6, 8, 'Understand and use mathematical notation'),
('Communication', 'Communication', 'Exchanging thoughts, messages and information effectively through interaction', 6, 8, 'Paraphrase accurately and concisely'),
('Social', 'Collaboration', 'Working effectively with others', 6, 8, 'Help others to succeed'),
('Social', 'Collaboration', 'Working effectively with others', 6, 8, 'Take responsibility for one''s own actions'),
('Self-management', 'Organization', 'Managing time and tasks effectively', 6, 8, 'Plan short- and long-term assignments; meet deadlines'),
('Self-management', 'Organization', 'Managing time and tasks effectively', 6, 8, 'Create plans to prepare for summative assessments'),
('Research', 'Information literacy', 'Finding, interpreting, judging and creating information', 6, 8, 'Collect and analyse data to identify solutions and make informed decisions'),
('Research', 'Information literacy', 'Finding, interpreting, judging and creating information', 6, 8, 'Process data and report results'),
('Thinking', 'Critical thinking', 'Analysing and evaluating issues and ideas', 6, 8, 'Practise observing carefully in order to recognize problems'),
('Thinking', 'Critical thinking', 'Analysing and evaluating issues and ideas', 6, 8, 'Gather and organize relevant information to formulate an argument');
