-- Migration: Create dedicated `pyp_unit` table for PYP Units of Inquiry (PostgreSQL / Supabase)
-- Date: 2026-08-13

CREATE TABLE IF NOT EXISTS public.pyp_unit (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title text NOT NULL,
    central_idea text NOT NULL,
    theme text NOT NULL DEFAULT 'Who We Are',
    duration_weeks integer DEFAULT 6,
    kelas_id bigint NOT NULL,
    year_id bigint,
    year_name text,
    status varchar(20) DEFAULT 'published',
    is_deleted smallint NOT NULL DEFAULT 0,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    created_by bigint NOT NULL DEFAULT 2,
    updated_at timestamp with time zone,
    updated_by bigint,
    deleted_at timestamp with time zone,
    deleted_by bigint
);

-- Enable RLS & Permissive Access Policies for Supabase
ALTER TABLE public.pyp_unit ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow all select pyp_unit" ON public.pyp_unit;
DROP POLICY IF EXISTS "Allow all insert pyp_unit" ON public.pyp_unit;
DROP POLICY IF EXISTS "Allow all update pyp_unit" ON public.pyp_unit;
DROP POLICY IF EXISTS "Allow all delete pyp_unit" ON public.pyp_unit;

CREATE POLICY "Allow all select pyp_unit" ON public.pyp_unit FOR SELECT USING (true);
CREATE POLICY "Allow all insert pyp_unit" ON public.pyp_unit FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow all update pyp_unit" ON public.pyp_unit FOR UPDATE USING (true);
CREATE POLICY "Allow all delete pyp_unit" ON public.pyp_unit FOR DELETE USING (true);
