-- Migration: create-pyp-subject-comment.sql
-- Description: Create pyp_subject_comment table for PYP Subject Teacher Comments (1 comment per student per subject per semester)

CREATE TABLE IF NOT EXISTS public.pyp_subject_comment (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  year_id BIGINT NOT NULL REFERENCES public.year(year_id) ON DELETE CASCADE,
  kelas_id BIGINT NOT NULL REFERENCES public.kelas(kelas_id) ON DELETE CASCADE,
  student_id BIGINT NOT NULL REFERENCES public.users(user_id) ON DELETE CASCADE,
  subject_id BIGINT NOT NULL REFERENCES public.pyp_subject(id) ON DELETE CASCADE,
  semester INTEGER NOT NULL CHECK (semester IN (1, 2)),
  comment_text TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),
  created_by BIGINT REFERENCES public.users(user_id) ON DELETE SET NULL,
  UNIQUE (year_id, kelas_id, student_id, subject_id, semester)
);

-- Indices for performance
CREATE INDEX IF NOT EXISTS idx_pyp_subject_comment_lookup 
  ON public.pyp_subject_comment (year_id, kelas_id, subject_id, semester);

CREATE INDEX IF NOT EXISTS idx_pyp_subject_comment_student 
  ON public.pyp_subject_comment (student_id);

-- Enable RLS and create open access policies for authenticated & anon clients
ALTER TABLE public.pyp_subject_comment ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Allow read access to pyp_subject_comment" ON public.pyp_subject_comment;
CREATE POLICY "Allow read access to pyp_subject_comment" ON public.pyp_subject_comment FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow full access to pyp_subject_comment" ON public.pyp_subject_comment;
CREATE POLICY "Allow full access to pyp_subject_comment" ON public.pyp_subject_comment FOR ALL USING (true) WITH CHECK (true);
